apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.images.mariadb }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.parameterGroupsMap.MARIADB_PORT }}
              name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.parameterGroupsMap.MARIADB_PASSWORD }}
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: mariadb-mount
              mountPath: /var/lib/mysql
          args:
            - "--innodb_flush_log_at_trx_commit=1"
            - "--innodb_max_dirty_pages_pct=0"
      volumes:
        - name: mariadb-mount
          hostPath:
            path: {{ $.Values.storage.mariadb.hostPath }}
